name: eeg_emotion_env
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - scipy=1.6.2
  - numpy=1.22.4
  - h5py=3.11.0
  - tqdm=4.66.1
  - networkx=3.1
  - pandas=2.0.3
  - logging=0.5.1.2
  - pip
  - pip:
      - torch==2.2.0+cu121
      - torch_geometric==2.6.1
      - torch_sparse==0.6.18+pt22cu121
      - torch_scatter==2.1.2+pt22cu121
      - argparse==1.1
